### ISSUE TITLE
ENOENT - Visual-studio-code-insiders

### ISSUE THREAD

**Issue by Its-Alex** [hangxingliu/vscode-coding-tracker#23]
I run this extension with visual studio code insiders, and I have this error

```
[Launch]: Local server launching...
[Error]: start local server failed!
Error: spawn node ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Error]: local server exit with code -2!(have you launch another local sever?)
[Exit] exit code: -2
```

This could be because extensions directory is `~/.vscode-insiders` instead of `~/.vscode` ?

**Comment by hangxingliu** [comment]
It seems like you have not install `Node.js`.   
Because extension launch a server written by Node.js in local server mode.

<https://nodejs.org>

---

And I will fix this error in the next version (replace `spawn` to `fork`)

**Comment by Its-Alex** [comment]
I have installed nodejs, I use nvm, can be due to this ?

**Comment by hangxingliu** [comment]
If you want keep your `nvm` environment. you can change some place in the extension sources:

Directory:    
`$HOME/.vscode-insiders/hangxingliu.vscode-coding-tracker-xxx/`

File:   
`lib/LocalServer.js`

Line **35**:   
``` javascript 
{ fork, spawn, exec } = require('child_process'),
```

Line **112**:   
``` javascript
var s = fork(EXECUTE_PARAMETERS[0], _getLaunchParameters().slice(1), { cwd: EXECUTE_CWD, silent: true });
```

And I will commit this patch to thr repository later

**Comment by Its-Alex** [comment]
Thanks ! I will try this
