### ISSUE TITLE
start local server failed!

### ISSUE THREAD

**Issue by skarone** [hangxingliu/vscode-coding-tracker#34]
Hi,
After installing the extension I got this error:

`[LocalMode]: try to kill old tracking server...
[LocalMode]: there are no old tracking server, just opening a new local server...
[Launch]: Local server launching...
[Error]: start local server failed!
Error: spawn node ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
	at onErrorNT (internal/child_process.js:406:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
[Error]: local server exit with code -2!(have you launch another local sever?)
[Exit] exit code: -2`

Do I have to install some dependency?
Or the extension will only work if I setup the server?

**Comment by skarone** [comment]
Please update documentation or catch error to notify user to install Node.js...
I'm closing this ticket
