### ISSUE TITLE
startup problem in vs code

### ISSUE THREAD

**Issue by pvojnisek** [hangxingliu/vscode-coding-tracker#37]
Coding Tracker is a really great idea, thank you for your efforts!
After installation to vs code from the marketplace I got continuous error messages.

	[LocalMode]: try to kill old tracking server...
	[LocalMode]: there are no old tracking server, just opening a new local server...
	[Launch]: Local server launching...
	[Error]: start local server failed!
	Error: spawn node ENOENT
		at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
		at onErrorNT (internal/child_process.js:407:16)
		at process._tickCallback (internal/process/next_tick.js:63:19)
	[Error]: local server exit with code -2!(have you launch another local sever?)
	[Exit] exit code: -2
	[Launch]: launching a new tracking server because detected old server exited!
	[Launch]: Local server launching...
	[Error]: start local server failed!
	Error: spawn node ENOENT
		at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
		at onErrorNT (internal/child_process.js:407:16)
		at process._tickCallback (internal/process/next_tick.js:63:19)
	[Error]: local server exit with code -2!(have you launch another local sever?)
	[Exit] exit code: -2
	[Launch]: launching a new tracking server because detected old server exited!
	[Launch]: Local server launching...
	[Error]: start local server failed!
	Error: spawn node ENOENT
		at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
		at onErrorNT (internal/child_process.js:407:16)
		at process._tickCallback (internal/process/next_tick.js:63:19)
	[Error]: local server exit with code -2!(have you launch another local sever?)
	[Exit] exit code: -2
	[Launch]: launching a new tracking server because detected old server exited!
	[Launch]: Local server launching...
	[Error]: start local server failed!
	Error: spawn node ENOENT
		at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
		at onErrorNT (internal/child_process.js:407:16)
		at process._tickCallback (internal/process/next_tick.js:63:19)
	[Error]: local server exit with code -2!(have you launch another local sever?)
	[Exit] exit code: -2
	[Launch]: launching a new tracking server because detected old server exited!
	[Launch]: Local server launching...
	[Error]: start local server failed!
	Error: spawn node ENOENT
		at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
		at onErrorNT (internal/child_process.js:407:16)
		at process._tickCallback (internal/process/next_tick.js:63:19)
	[Error]: local server exit with code -2!(have you launch another local sever?)
	[Exit] exit code: -2

![image](https://user-images.githubusercontent.com/45441/67547071-53d36600-f6fe-11e9-9804-90a758fb4b74.png)

VS Code version:

	Version: 1.39.2
	Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
	Date: 2019-10-15T15:33:40.634Z
	Electron: 4.2.10
	Chrome: 69.0.3497.128
	Node.js: 10.11.0
	V8: 6.9.427.31-electron.0
	OS: Linux x64 4.15.0-66-generic

**Comment by dannyycchan** [comment]
Same

**Comment by danchann** [comment]
same

**Comment by devscheffer** [comment]
same

**Comment by robgal519** [comment]
I had the same issue, but I was using WSL.

To fix this issue, I had to install npm on my ubuntu WSL.
Now everything works fine

**Comment by personaaleatoria** [comment]
same

Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-15T11:13:06.921Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-52-generic
