### ISSUE TITLE
Can't start the extension

### ISSUE THREAD

**Issue by Developer8814** [hangxingliu/vscode-coding-tracker#46]
Hi!

I can't start the extension the extension says:

[Launch]: launching a new tracking server because detected old server exited!
[Launch]: Local server launching...
[Error]: start local server failed!
Error: spawn node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[Error]: local server exit with code -2!(have you launch another local sever?)
[Exit] exit code: -2

i'm on debian 10

**Comment by tonysummerfelt** [comment]
Same. Pop_OS 20.04 (Ubuntu)
